### ISSUE TITLE
I drag but it falls off

### ISSUE THREAD

**Issue by QQQ-Q** [TristanH/bookcision#2]
I drag the image/bookmarklet to the bookmark bar as indicated but it falls away and won't stick. Was this made for a previous version of Chrome? I'm using the up to date
Version 69.0.3497.100 (Official Build) (64-bit)

Is there an alternate way to install?

**Comment by TristanH** [comment]
Hey @QQQ-Q -- this is indeed an issue with the latest version of Chrome (69) 😢 

You can read more about the bug here: https://support.talis.com/hc/en-us/articles/360000426317-Installing-Talis-Aspire-bookmarklet-in-Chrome-Version-69-

The good news is that it is expected to be fixed in Chrome 70 (shipping mid-October, hopefully)!

In the mean time, you can do the onerous process described in the link above of right clicking the "Drag to Bookmarks Bar" button, pressing "Copy link address" and creating the bookmark in the Chrome Bookmarks manager. I've confirmed that that still works.

Hope that helps! Let me know if I can do anything else.
